<a href="https://colab.research.google.com/github/WellingtonRoque/MineracaoDados/blob/main/atividades/aula5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4. EXTRACT — Extraindo dados
Vamos simular três arquivos CSV.

Primeiro criaremos os DataFrames que representarão as fontes.

In [1]:
import pandas as pd
import numpy as np


sensores = pd.DataFrame({
    "motor": ["M001", "M001", "M002", "M002", "M003", "M003"],
    "data_hora": [
        "2026-02-01 08:00", "2026-02-01 09:00",
        "2026-02-01 08:00", "2026-02-01 09:00",
        "2026-02-01 08:00", "2026-02-01 09:00"
    ],
    "corrente": [12.4, 12.8, 10.8, 11.0, 14.1, 14.3],
    "tensao": [380, 379, 380, 381, 382, 381],
    "vibracao": [1.8, 2.1, 1.2, 1.3, 2.4, 2.6],
    "temperatura": [62.3, 64.1, 55.1, 56.0, 67.2, 68.4],
    "rpm": [1750, 1748, 1752, 1750, 1740, 1738]
})

sensores

  motor         data_hora  corrente  tensao  vibracao  temperatura   rpm
0  M001  2026-02-01 08:00      12.4     380       1.8         62.3  1750
1  M001  2026-02-01 09:00      12.8     379       2.1         64.1  1748
2  M002  2026-02-01 08:00      10.8     380       1.2         55.1  1752
3  M002  2026-02-01 09:00      11.0     381       1.3         56.0  1750
4  M003  2026-02-01 08:00      14.1     382       2.4         67.2  1740
5  M003  2026-02-01 09:00      14.3     381       2.6         68.4  1738

In [2]:
cadastro = pd.DataFrame({
    "motor": ["M001", "M002", "M003"],
    "modelo": ["MX-100", "MX-100", "MX-200"],
    "fabricante": ["MotorTech", "MotorTech", "PowerMotor"],
    "potencia_nominal": [7.5, 6.5, 9.0],
    "linha": ["Linha A", "Linha A", "Linha B"]
})

cadastro

  motor  modelo  fabricante  potencia_nominal    linha
0  M001  MX-100   MotorTech               7.5  Linha A
1  M002  MX-100   MotorTech               6.5  Linha A
2  M003  MX-200  PowerMotor               9.0  Linha B

In [3]:
manutencao = pd.DataFrame({
    "motor": ["M001", "M002", "M003"],
    "ultima_manutencao": ["2026-01-15", "2026-01-20", "2025-12-18"],
    "horas_operacao": [1254, 824, 2104],
    "status_manutencao": ["Em dia", "Em dia", "Atenção"]
})

manutencao

  motor ultima_manutencao  horas_operacao status_manutencao
0  M001        2026-01-15            1254            Em dia
1  M002        2026-01-20             824            Em dia
2  M003        2025-12-18            2104           Atenção

In [4]:
sensores.dtypes

motor           object
data_hora       object
corrente       float64
tensao           int64
vibracao       float64
temperatura    float64
rpm              int64
dtype: object

In [5]:
cadastro.dtypes

motor                object
modelo               object
fabricante           object
potencia_nominal    float64
linha                object
dtype: object

In [6]:
manutencao.dtypes

motor                object
ultima_manutencao    object
horas_operacao        int64
status_manutencao    object
dtype: object

Datas devem ser convertidas para tipos adequados.

In [7]:
sensores["data_hora"] = pd.to_datetime(sensores["data_hora"])
manutencao["ultima_manutencao"] = pd.to_datetime(manutencao["ultima_manutencao"])

sensores.dtypes

motor                  object
data_hora      datetime64[ns]
corrente              float64
tensao                  int64
vibracao              float64
temperatura           float64
rpm                     int64
dtype: object

Padronizando textos
Também podemos remover espaços desnecessários e padronizar textos.

In [8]:
cadastro["fabricante"] = cadastro["fabricante"].str.strip()
cadastro["linha"] = cadastro["linha"].str.strip()

cadastro

  motor  modelo  fabricante  potencia_nominal    linha
0  M001  MX-100   MotorTech               7.5  Linha A
1  M002  MX-100   MotorTech               6.5  Linha A
2  M003  MX-200  PowerMotor               9.0  Linha B

6. TRANSFORM — Combinando dados
Agora temos três DataFrames.

Precisamos relacioná-los.

A coluna motor funciona como uma chave para fazer a combinação.

Podemos utilizar merge().

In [9]:
dados_etl = sensores.merge(
    cadastro,
    on="motor",
    how="left"
)

dados_etl

,motor,data_hora,corrente,tensao,vibracao,temperatura,rpm,modelo,fabricante,potencia_nominal,linha
0,M001,2026-02-01 08:00:00,12.4,380,1.8,62.3,1750,MX-100,MotorTech,7.5,Linha A
1,M001,2026-02-01 09:00:00,12.8,379,2.1,64.1,1748,MX-100,MotorTech,7.5,Linha A
2,M002,2026-02-01 08:00:00,10.8,380,1.2,55.1,1752,MX-100,MotorTech,6.5,Linha A
3,M002,2026-02-01 09:00:00,11.0,381,1.3,56.0,1750,MX-100,MotorTech,6.5,Linha A
4,M003,2026-02-01 08:00:00,14.1,382,2.4,67.2,1740,MX-200,PowerMotor,9.0,Linha B
5,M003,2026-02-01 09:00:00,14.3,381,2.6,68.4,1738,MX-200,PowerMotor,9.0,Linha B

Agora vamos incorporar os dados de manutenção.

In [10]:
dados_etl = dados_etl.merge(
    manutencao,
    on="motor",
    how="left"
)

dados_etl

,motor,data_hora,corrente,tensao,vibracao,temperatura,rpm,modelo,fabricante,potencia_nominal,linha,ultima_manutencao,horas_operacao,status_manutencao
0,M001,2026-02-01 08:00:00,12.4,380,1.8,62.3,1750,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia
1,M001,2026-02-01 09:00:00,12.8,379,2.1,64.1,1748,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia
2,M002,2026-02-01 08:00:00,10.8,380,1.2,55.1,1752,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia
3,M002,2026-02-01 09:00:00,11.0,381,1.3,56.0,1750,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia
4,M003,2026-02-01 08:00:00,14.1,382,2.4,67.2,1740,MX-200,PowerMotor,9.0,Linha B,2025-12-18,2104,Atenção
5,M003,2026-02-01 09:00:00,14.3,381,2.6,68.4,1738,MX-200,PowerMotor,9.0,Linha B,2025-12-18,2104,Atenção

7. Criando novas informações
Durante a transformação podemos criar novas variáveis.

Por exemplo, podemos calcular a diferença entre a potência medida e a potência nominal.

Para isso, primeiro vamos criar uma potência medida simplificada para fins didáticos.

In [11]:
dados_etl["potencia_medida"] = (
    dados_etl["corrente"] * dados_etl["tensao"] / 1000
)

dados_etl[[
    "motor",
    "corrente",
    "tensao",
    "potencia_medida",
    "potencia_nominal"
]]

  motor  corrente  tensao  potencia_medida  potencia_nominal
0  M001      12.4     380           4.7120               7.5
1  M001      12.8     379           4.8512               7.5
2  M002      10.8     380           4.1040               6.5
3  M002      11.0     381           4.1910               6.5
4  M003      14.1     382           5.3862               9.0
5  M003      14.3     381           5.4483               9.0

Agora podemos criar uma variável de diferença.

In [12]:
dados_etl["diferenca_potencia"] = (
    dados_etl["potencia_medida"] - dados_etl["potencia_nominal"]
)

dados_etl[[
    "motor",
    "potencia_medida",
    "potencia_nominal",
    "diferenca_potencia"
]]

  motor  potencia_medida  potencia_nominal  diferenca_potencia
0  M001           4.7120               7.5             -2.7880
1  M001           4.8512               7.5             -2.6488
2  M002           4.1040               6.5             -2.3960
3  M002           4.1910               6.5             -2.3090
4  M003           5.3862               9.0             -3.6138
5  M003           5.4483               9.0             -3.5517

8. Transformação e qualidade

Vamos verificar se a base integrada possui problemas.

In [16]:
#dados_etl.info()

#dados_etl.isnull().sum()

#dados_etl.duplicated().sum()

np.int64(0)

9. LOAD — Carregando os dados
Depois da transformação, podemos salvar a base.

Uma opção simples é CSV.

In [17]:
arquivo_saida = "motores_etl.csv"

dados_etl.to_csv(arquivo_saida, index=False)

print("Arquivo criado:", arquivo_saida)

Arquivo criado: motores_etl.csv

Podemos conferir o arquivo carregando-o novamente.

In [18]:
dados_carregados = pd.read_csv(arquivo_saida)

dados_carregados.head()

,motor,data_hora,corrente,tensao,vibracao,temperatura,rpm,modelo,fabricante,potencia_nominal,linha,ultima_manutencao,horas_operacao,status_manutencao,potencia_medida,diferenca_potencia
0,M001,2026-02-01 08:00:00,12.4,380,1.8,62.3,1750,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia,4.7120,-2.7880
1,M001,2026-02-01 09:00:00,12.8,379,2.1,64.1,1748,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia,4.8512,-2.6488
2,M002,2026-02-01 08:00:00,10.8,380,1.2,55.1,1752,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia,4.1040,-2.3960
3,M002,2026-02-01 09:00:00,11.0,381,1.3,56.0,1750,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia,4.1910,-2.3090
4,M003,2026-02-01 08:00:00,14.1,382,2.4,67.2,1740,MX-200,PowerMotor,9.0,Linha B,2025-12-18,2104,Atenção,5.3862,-3.6138

10. Construindo um fluxo ETL
Agora vamos organizar o processo em funções.

Isso deixa o código mais reutilizável.

In [19]:
def extrair_dados():
    sensores = pd.DataFrame({
        "motor": ["M001", "M001", "M002", "M002", "M003", "M003"],
        "data_hora": [
            "2026-02-01 08:00", "2026-02-01 09:00",
            "2026-02-01 08:00", "2026-02-01 09:00",
            "2026-02-01 08:00", "2026-02-01 09:00"
        ],
        "corrente": [12.4, 12.8, 10.8, 11.0, 14.1, 14.3],
        "tensao": [380, 379, 380, 381, 382, 381],
        "vibracao": [1.8, 2.1, 1.2, 1.3, 2.4, 2.6],
        "temperatura": [62.3, 64.1, 55.1, 56.0, 67.2, 68.4],
        "rpm": [1750, 1748, 1752, 1750, 1740, 1738]
    })

    cadastro = pd.DataFrame({
        "motor": ["M001", "M002", "M003"],
        "modelo": ["MX-100", "MX-100", "MX-200"],
        "fabricante": ["MotorTech", "MotorTech", "PowerMotor"],
        "potencia_nominal": [7.5, 6.5, 9.0],
        "linha": ["Linha A", "Linha A", "Linha B"]
    })

    manutencao = pd.DataFrame({
        "motor": ["M001", "M002", "M003"],
        "ultima_manutencao": ["2026-01-15", "2026-01-20", "2025-12-18"],
        "horas_operacao": [1254, 824, 2104],
        "status_manutencao": ["Em dia", "Em dia", "Atenção"]
    })

    return sensores, cadastro, manutencao

In [20]:
def transformar_dados(sensores, cadastro, manutencao):
    sensores["data_hora"] = pd.to_datetime(sensores["data_hora"])
    manutencao["ultima_manutencao"] = pd.to_datetime(
        manutencao["ultima_manutencao"]
    )

    cadastro["fabricante"] = cadastro["fabricante"].str.strip()
    cadastro["linha"] = cadastro["linha"].str.strip()

    dados = sensores.merge(cadastro, on="motor", how="left")
    dados = dados.merge(manutencao, on="motor", how="left")

    dados["potencia_medida"] = (
        dados["corrente"] * dados["tensao"] / 1000
    )

    dados["diferenca_potencia"] = (
        dados["potencia_medida"] - dados["potencia_nominal"]
    )

    return dados

In [21]:
def carregar_dados(dados, arquivo="motores_etl_final.csv"):
    dados.to_csv(arquivo, index=False)
    return arquivo

In [22]:
sensores, cadastro, manutencao = extrair_dados()

dados_finais = transformar_dados(
    sensores,
    cadastro,
    manutencao
)

arquivo = carregar_dados(dados_finais)

print("Processo ETL concluído!")
print("Arquivo:", arquivo)

dados_finais

Processo ETL concluído!
Arquivo: motores_etl_final.csv

,motor,data_hora,corrente,tensao,vibracao,temperatura,rpm,modelo,fabricante,potencia_nominal,linha,ultima_manutencao,horas_operacao,status_manutencao,potencia_medida,diferenca_potencia
0,M001,2026-02-01 08:00:00,12.4,380,1.8,62.3,1750,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia,4.7120,-2.7880
1,M001,2026-02-01 09:00:00,12.8,379,2.1,64.1,1748,MX-100,MotorTech,7.5,Linha A,2026-01-15,1254,Em dia,4.8512,-2.6488
2,M002,2026-02-01 08:00:00,10.8,380,1.2,55.1,1752,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia,4.1040,-2.3960
3,M002,2026-02-01 09:00:00,11.0,381,1.3,56.0,1750,MX-100,MotorTech,6.5,Linha A,2026-01-20,824,Em dia,4.1910,-2.3090
4,M003,2026-02-01 08:00:00,14.1,382,2.4,67.2,1740,MX-200,PowerMotor,9.0,Linha B,2025-12-18,2104,Atenção,5.3862,-3.6138
5,M003,2026-02-01 09:00:00,14.3,381,2.6,68.4,1738,MX-200,PowerMotor,9.0,Linha B,2025-12-18,2104,Atenção,5.4483,-3.5517