<a href="https://colab.research.google.com/github/WellingtonRoque/MineracaoDados/blob/main/atividades/aula6_exemploWEB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Isso é perfeito para transformar a Aula 06 em um exemplo real.

Proposta para o Colab

Vamos fazer:

🌐 Página real da WEG

        ↓

📥 Requests

        ↓

🥣 BeautifulSoup

        ↓

🔎 Encontrar informações técnicas

        ↓
        
📊 DataFrame Pandas

**célula de diagnóstico**

E explicar:

200 → acesso permitido

403 → acesso proibido

404 → página não encontrada

500 → erro no **servidor**

In [1]:
import requests

url = "https://www.weg.net/catalog/weg/BR/pt/Motores-El%C3%A9tricos/Trifásico---Baixa-Tensão/Uso-Geral/W22/W22-/W22-IR3-Premium-7-5-cv-4P-L112M-3F-220-380-V-60-Hz-IC411---TFVE---B35D/p/12460578"

resposta = requests.get(url)

print("Status:", resposta.status_code)
print("Tamanho:", len(resposta.text))

Status: 403
Tamanho: 715

In [2]:
import requests

url = "https://loja.herculesmotores.com.br/motor-eletrico-trifasico-standard/ip55/3cv/4p/220/380/motor-eltrico-trifsico-standard-ip55-3cv-4p-220-380-440v-b35d.html"

resposta = requests.get(url)

print("Status:", resposta.status_code)
print("Tamanho:", len(resposta.text))

Status: 200
Tamanho: 226977

1. Interpretar o HTML com BeautifulSoup

Crie uma nova célula e execute:

In [3]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(resposta.text, "html.parser")

print("Título da página:")
print(soup.title.text)

Título da página:
Motor trifásico IEC90 IP55 3CV 4P 220/380/440V B35D | Hercules Motores

2. Vamos verificar o conteúdo da página

Depois execute:

In [4]:
print(soup.get_text(" ", strip=True)[:5000])

Motor trifásico IEC90 IP55 3CV 4P 220/380/440V B35D | Hercules Motores The store will not work correctly when cookies are disabled. O JavaScript parece estar desabilitado no seu navegador. Para ter uma melhor experiência em nosso site, certifique-se de ativar o javascript em seu navegador. Alternar Nav Comparar Produtos Pesquisa Pesquisa Pesquisa Avançada Pesquisa Entrar Criar Conta Acessar minha Conta Entre ou cadastre-se Receber código de acesso Acompanhar pedido Já sou cadastrado Para entrar ou criar uma conta através do seu login social, acesse uma das opções: Entre com o Google Receba o código de acesso por e-email Email Apenas para clientes com cadastro. Conta não encontrada, por favor verifique o email digitado. Voltar Enviar Insira aqui o código recebido por e-mail Algo deu errado, por favor verifique o código digitado ou entre em contato conosco. Voltar Validar Código Acompanhar pedido Email Um link de acesso será enviado a seu e-mail Algo deu errado, por favor verifique o email digitado. Voltar Enviar Se houver algum pedido vinculado ao email digitado, você receberá um link de acesso no seu email. Voltar Central de Atendimento Fale Conosco Loja Virtual (47) 3281-1986 Horário de atendimento Segunda à sexta das 8h às 12h e das 13h às 17h exceto feriados loja@herculesmotores.com.br Encontre a assistência mais proxima Assistência Técnica Possui alguma dúvida? Acesse nosso FAQ Minha Lista de Desejos Meu Carrinho 0 Menu Monofásico Alimentício Aviário Automatizador de portão Betoneira Bomba de piscina Climatização e Ventilação Compressores Centrífuga de roupas Lavadora de roupas Secadora de roupas Secador pet Ferramentaria Monofásico Especial Monofásicos JM Monofásico Premium Monofásico IP21 Monofásico IP44 Monofásico IP55 Monofásico para redutor View All of Monofásico Trifásico Trifásico IP21 Trifásico IP44 Trifásico IP55 Trifásico para bomba Trifásico Especial Trifásico JM Trifásico Jet Pump Trifásico com rolamento bloqueado Alimentício Carro elétrico Climatização e Ventilação Centrífuga de sangue Elevador automotivo Esteira ergométrica View All of Trifásico Motofreio Motorredutor Motorredutor trifásico Motorredutor monofásico View All of Motorredutor Inversor de frequência Redutores Linha lavanderia Peças Flanges Tampas e calotas Sistema Hercules de proteção Rolamentos Conjunto centrífugo Placas de borne e prensa cabos Capacitores Conjunto platinado Kit freio KIt reparo freio Pé Nema Capa do capacitor Arruela ondulada Chaveta Ventiladores Conjunto de Rotor Conjunto estrator Estator Anel de retenção Centrifugo rural View All of Peças Ofertas Conta Pular para o final da Galeria de imagens Saltar para o início da Galeria de imagens Compartilhar Motor trifásico IEC90 IP55 3CV 4P 220/380/440V B35D Produto original, 100% nacional, direto de fábrica e com garantia de 2 anos. Ref. 606547412 R$ 2.673,53 à vista no pix (5% de desconto) no boleto (5% de desconto) R$ 3.517,80 adicionar ao carrinho R$ 2.673,53 no boleto bancário
            (5% de desconto) Em estoque Ref 606547412 Calcule o frete para a sua região Calcular Não sabe o CEP? Adicionar à lista de desejos Adicionar para Comparar Motor elétrico trifásico standard IP55 3CV 4P 220/380/440V B35D Medidas do Produto Altura 19,9 Largura 24,2 Profundidade 33,5 Especificações técnicas Desconto no Pix 5 Descrição Motor trifásico IEC90 IP55 3CV 4P 220/380/440V Potência 3CV Tensão 220/380/440V Polaridade 4 Polos Frequência 60Hz Rotação 1740 RPM Sentido do giro Ambos Flange FF-165 Classe de Isolação F Corrente Nominal (A) 8,89/5,13/4,44 A Regime de Serviço S1 Fator de Serviço 1,25 Grau de Proteção IP55 Tipo de Carcaça IEC90 Forma Construtiva B35D Caixa de Ligação Direita Fixação Pés Cor Ral-7026 Altura (cm) 19,9 Largura (cm) 24,2 Profundidade (cm) 33,5 Peso aprox. 18,5Kg Garantia 2 Anos Especificações técnicas Especificações técnicas Desconto no Pix 5 Descrição Motor trifásico IEC90 IP55 3CV 4P 220/380/440V Potência 3CV Tensão 220/380/440V Polaridade 4 Polos Frequência 60Hz Rotação 1740 RPM Sentido do giro Ambos Flange FF-165 Classe de Isolação F Corrente Nominal (A) 8,89/5,13/4,44 A Regime de Serviço S1 Fator de Serviço 1,25 Grau de Proteção IP55 Tipo de Carcaça IEC90 Forma Construtiva B35D Caixa de Ligação Direita Fixação Pés Cor Ral-7026 Altura (cm) 19,9 Largura (cm) 24,2 Profundidade (cm) 33,5 Peso aprox. 18,5Kg Garantia 2 Anos Receba nossas ofertas e lançamentos Cadastre-se agora e ganha um cupom de 5% de desconto na primeira compra Cadastrar Li e estou de acordo com os termos da Política de Privacidade e estou de acordo e aceito receber e-mails marketing e/ou promocionais da Hercules. Empresa do grupo: Empresa do grupo: Conheça nossas Redes Sociais Sobre A
                                Hercules FAQ Contato Assistência Técnica Código de Conduta Canal
                                de Denúncias Nosso Blog Formas
                                Construtivas do Motor Manuais Políticas Política de
                                Entrega Política

3. Localizar as tabelas da página

Como estamos procurando especificações técnicas, vamos verificar se a página possui tabelas HTML:

In [5]:
tabelas = soup.find_all("table")

print("Quantidade de tabelas encontradas:", len(tabelas))

Quantidade de tabelas encontradas: 2

Se aparecer, por exemplo:

Quantidade de tabelas encontradas: 3

podemos inspecionar cada uma:

In [6]:
for i, tabela in enumerate(tabelas):
    print(f"\n--- TABELA {i} ---")
    print(tabela.get_text(" ", strip=True)[:2000])

--- TABELA 0 ---
Especificações técnicas Desconto no Pix 5 Descrição Motor trifásico IEC90 IP55 3CV 4P 220/380/440V Potência 3CV Tensão 220/380/440V Polaridade 4 Polos Frequência 60Hz Rotação 1740 RPM Sentido do giro Ambos Flange FF-165 Classe de Isolação F Corrente Nominal (A) 8,89/5,13/4,44 A Regime de Serviço S1 Fator de Serviço 1,25 Grau de Proteção IP55 Tipo de Carcaça IEC90 Forma Construtiva B35D Caixa de Ligação Direita Fixação Pés Cor Ral-7026 Altura (cm) 19,9 Largura (cm) 24,2 Profundidade (cm) 33,5 Peso aprox. 18,5Kg Garantia 2 Anos

--- TABELA 1 ---
Especificações técnicas Desconto no Pix 5 Descrição Motor trifásico IEC90 IP55 3CV 4P 220/380/440V Potência 3CV Tensão 220/380/440V Polaridade 4 Polos Frequência 60Hz Rotação 1740 RPM Sentido do giro Ambos Flange FF-165 Classe de Isolação F Corrente Nominal (A) 8,89/5,13/4,44 A Regime de Serviço S1 Fator de Serviço 1,25 Grau de Proteção IP55 Tipo de Carcaça IEC90 Forma Construtiva B35D Caixa de Ligação Direita Fixação Pés Cor Ral-7026 Altura (cm) 19,9 Largura (cm) 24,2 Profundidade (cm) 33,5 Peso aprox. 18,5Kg Garantia 2 Anos

4. Ver a estrutura das linhas da tabela

Execute esta célula:

In [7]:
for i, tabela in enumerate(tabelas):

    print(f"\n========== TABELA {i} ==========")

    linhas = tabela.find_all("tr")

    print("Quantidade de linhas:", len(linhas))

    for linha in linhas:
        colunas = linha.find_all(["th", "td"])

        valores = [coluna.get_text(" ", strip=True) for coluna in colunas]

        print(valores)

========== TABELA 0 ==========
Quantidade de linhas: 24
['Desconto no Pix', '5']
['Descrição', 'Motor trifásico IEC90 IP55 3CV 4P 220/380/440V']
['Potência', '3CV']
['Tensão', '220/380/440V']
['Polaridade', '4 Polos']
['Frequência', '60Hz']
['Rotação', '1740 RPM']
['Sentido do giro', 'Ambos']
['Flange', 'FF-165']
['Classe de Isolação', 'F']
['Corrente Nominal (A)', '8,89/5,13/4,44 A']
['Regime de Serviço', 'S1']
['Fator de Serviço', '1,25']
['Grau de Proteção', 'IP55']
['Tipo de Carcaça', 'IEC90']
['Forma Construtiva', 'B35D']
['Caixa de Ligação', 'Direita']
['Fixação', 'Pés']
['Cor', 'Ral-7026']
['Altura (cm)', '19,9']
['Largura (cm)', '24,2']
['Profundidade (cm)', '33,5']
['Peso aprox.', '18,5Kg']
['Garantia', '2 Anos']

========== TABELA 1 ==========
Quantidade de linhas: 24
['Desconto no Pix', '5']
['Descrição', 'Motor trifásico IEC90 IP55 3CV 4P 220/380/440V']
['Potência', '3CV']
['Tensão', '220/380/440V']
['Polaridade', '4 Polos']
['Frequência', '60Hz']
['Rotação', '1740 RPM']
['Sentido do giro', 'Ambos']
['Flange', 'FF-165']
['Classe de Isolação', 'F']
['Corrente Nominal (A)', '8,89/5,13/4,44 A']
['Regime de Serviço', 'S1']
['Fator de Serviço', '1,25']
['Grau de Proteção', 'IP55']
['Tipo de Carcaça', 'IEC90']
['Forma Construtiva', 'B35D']
['Caixa de Ligação', 'Direita']
['Fixação', 'Pés']
['Cor', 'Ral-7026']
['Altura (cm)', '19,9']
['Largura (cm)', '24,2']
['Profundidade (cm)', '33,5']
['Peso aprox.', '18,5Kg']
['Garantia', '2 Anos']

5. Criar um dicionário com os dados extraídos

Vamos usar a primeira tabela:

In [8]:
tabela = tabelas[0]

dados_motor = {}

linhas = tabela.find_all("tr")

for linha in linhas:
    colunas = linha.find_all(["th", "td"])

    valores = [coluna.get_text(" ", strip=True) for coluna in colunas]

    if len(valores) == 2:
        chave = valores[0]
        valor = valores[1]

        dados_motor[chave] = valor

dados_motor

{'Desconto no Pix': '5',
 'Descrição': 'Motor trifásico IEC90 IP55 3CV 4P 220/380/440V',
 'Potência': '3CV',
 'Tensão': '220/380/440V',
 'Polaridade': '4 Polos',
 'Frequência': '60Hz',
 'Rotação': '1740 RPM',
 'Sentido do giro': 'Ambos',
 'Flange': 'FF-165',
 'Classe de Isolação': 'F',
 'Corrente Nominal (A)': '8,89/5,13/4,44 A',
 'Regime de Serviço': 'S1',
 'Fator de Serviço': '1,25',
 'Grau de Proteção': 'IP55',
 'Tipo de Carcaça': 'IEC90',
 'Forma Construtiva': 'B35D',
 'Caixa de Ligação': 'Direita',
 'Fixação': 'Pés',
 'Cor': 'Ral-7026',
 'Altura (cm)': '19,9',
 'Largura (cm)': '24,2',
 'Profundidade (cm)': '33,5',
 'Peso aprox.': '18,5Kg',
 'Garantia': '2 Anos'}

6. Transformar em DataFrame

Agora vamos usar o Pandas:

In [10]:
import pandas as pd

df_motor = pd.DataFrame([dados_motor])

df_motor

,Desconto no Pix,Descrição,Potência,Tensão,Polaridade,Frequência,Rotação,Sentido do giro,Flange,Classe de Isolação,...,Tipo de Carcaça,Forma Construtiva,Caixa de Ligação,Fixação,Cor,Altura (cm),Largura (cm),Profundidade (cm),Peso aprox.,Garantia
0,5,Motor trifásico IEC90 IP55 3CV 4P 220/380/440V,3CV,220/380/440V,4 Polos,60Hz,1740 RPM,Ambos,FF-165,F,...,IEC90,B35D,Direita,Pés,Ral-7026,"19,9","24,2","33,5","18,5Kg",2 Anos

7. Selecionar somente os dados importantes

Para a nossa aula, não precisamos trabalhar inicialmente com todas as 24 informações. Vamos selecionar os principais dados técnicos do motor.

Execute:

In [14]:
colunas_interesse = [
    "Descrição",
    "Potência",
    "Tensão",
    "Polaridade",
    "Frequência",
    "Rotação",
    "Corrente Nominal (A)",
    "Classe de Isolação",
    "Fator de Serviço",
    "Grau de Proteção",
    "Tipo de Carcaça",
    "Forma Construtiva",
    "Peso aprox."
]

df_tecnico = df_motor[colunas_interesse].copy()

df_tecnico

,Descrição,Potência,Tensão,Polaridade,Frequência,Rotação,Corrente Nominal (A),Classe de Isolação,Fator de Serviço,Grau de Proteção,Tipo de Carcaça,Forma Construtiva,Peso aprox.
0,Motor trifásico IEC90 IP55 3CV 4P 220/380/440V,3CV,220/380/440V,4 Polos,60Hz,1740 RPM,"8,89/5,13/4,44 A",F,"1,25",IP55,IEC90,B35D,"18,5Kg"

8. Verificar os tipos dos dados

Agora vem uma etapa muito importante de ETL.

Execute:

In [15]:
df_tecnico.dtypes

Descrição               object
Potência                object
Tensão                  object
Polaridade              object
Frequência              object
Rotação                 object
Corrente Nominal (A)    object
Classe de Isolação      object
Fator de Serviço        object
Grau de Proteção        object
Tipo de Carcaça         object
Forma Construtiva       object
Peso aprox.             object
dtype: object

Isso é justamente o problema de ETL que queremos demonstrar.

Agora execute a limpeza

Vamos fazer tudo em uma única célula, para evitar problemas de execução fora de ordem:

In [16]:
# Limpeza e conversão dos dados

df_tecnico["Potência"] = (
    df_tecnico["Potência"]
    .astype(str)
    .str.replace("CV", "", regex=False)
    .str.strip()
    .astype(float)
)

df_tecnico["Frequência"] = (
    df_tecnico["Frequência"]
    .astype(str)
    .str.replace("Hz", "", regex=False)
    .str.strip()
    .astype(float)
)

df_tecnico["Rotação"] = (
    df_tecnico["Rotação"]
    .astype(str)
    .str.replace("RPM", "", regex=False)
    .str.strip()
    .astype(int)
)

df_tecnico["Fator de Serviço"] = (
    df_tecnico["Fator de Serviço"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .str.strip()
    .astype(float)
)

df_tecnico["Peso aprox."] = (
    df_tecnico["Peso aprox."]
    .astype(str)
    .str.replace("Kg", "", regex=False)
    .str.replace(",", ".", regex=False)
    .str.strip()
    .astype(float)
)

df_tecnico

,Descrição,Potência,Tensão,Polaridade,Frequência,Rotação,Corrente Nominal (A),Classe de Isolação,Fator de Serviço,Grau de Proteção,Tipo de Carcaça,Forma Construtiva,Peso aprox.
0,Motor trifásico IEC90 IP55 3CV 4P 220/380/440V,3.0,220/380/440V,4 Polos,60.0,1740,"8,89/5,13/4,44 A",F,1.25,IP55,IEC90,B35D,18.5

8. Transformar a Tensão

Atualmente temos:

220/380/440V

Vamos retirar o V e separar os três valores:

In [19]:
df_tecnico["Tensão"] = (
    df_tecnico["Tensão"]
    .astype(str)
    .str.replace("V", "", regex=False)
    .str.strip()
)

df_tecnico["Tensão"]

0    220/380/440
Name: Tensão, dtype: object

Agora podemos separar:

In [20]:
tensoes = df_tecnico["Tensão"].str.split("/", expand=True)

tensoes.columns = ["Tensão_1", "Tensão_2", "Tensão_3"]

tensoes

  Tensão_1 Tensão_2 Tensão_3
0      220      380      440

E podemos transformar em números:

In [21]:
tensoes = tensoes.astype(float)

tensoes

   Tensão_1  Tensão_2  Tensão_3
0     220.0     380.0     440.0

9. Fazer o mesmo com a corrente

A corrente veio assim:

8,89/5,13/4,44 A

In [22]:
df_tecnico["Corrente Nominal (A)"] = (
    df_tecnico["Corrente Nominal (A)"]
    .astype(str)
    .str.replace("A", "", regex=False)
    .str.replace(",", ".", regex=False)
    .str.strip()
)

Agora:

In [23]:
correntes = df_tecnico["Corrente Nominal (A)"].str.split("/", expand=True)

correntes.columns = [
    "Corrente_1",
    "Corrente_2",
    "Corrente_3"
]

correntes = correntes.astype(float)

correntes

   Corrente_1  Corrente_2  Corrente_3
0        8.89        5.13        4.44

10. Juntar tudo no DataFrame

Agora podemos incorporar essas novas colunas:

In [24]:
df_tecnico = pd.concat(
    [
        df_tecnico,
        tensoes,
        correntes
    ],
    axis=1
)

df_tecnico

,Descrição,Potência,Tensão,Polaridade,Frequência,Rotação,Corrente Nominal (A),Classe de Isolação,Fator de Serviço,Grau de Proteção,Tipo de Carcaça,Forma Construtiva,Peso aprox.,Tensão_1,Tensão_2,Tensão_3,Corrente_1,Corrente_2,Corrente_3
0,Motor trifásico IEC90 IP55 3CV 4P 220/380/440V,3.0,220/380/440,4 Polos,60.0,1740,8.89/5.13/4.44,F,1.25,IP55,IEC90,B35D,18.5,220.0,380.0,440.0,8.89,5.13,4.44

11. Conferir todas as colunas

Execute:

In [26]:
print(df_tecnico.columns.tolist())

print(df_tecnico.shape)

['Descrição', 'Potência', 'Tensão', 'Polaridade', 'Frequência', 'Rotação', 'Corrente Nominal (A)', 'Classe de Isolação', 'Fator de Serviço', 'Grau de Proteção', 'Tipo de Carcaça', 'Forma Construtiva', 'Peso aprox.', 'Tensão_1', 'Tensão_2', 'Tensão_3', 'Corrente_1', 'Corrente_2', 'Corrente_3']
(1, 19)

12. Visualizar somente os dados numéricos

Agora vamos separar os atributos que podem ser utilizados diretamente em cálculos:

In [27]:
colunas_numericas = [
    "Potência",
    "Frequência",
    "Rotação",
    "Fator de Serviço",
    "Peso aprox.",
    "Tensão_1",
    "Tensão_2",
    "Tensão_3",
    "Corrente_1",
    "Corrente_2",
    "Corrente_3"
]

df_numerico = df_tecnico[colunas_numericas]

df_numerico

,Potência,Frequência,Rotação,Fator de Serviço,Peso aprox.,Tensão_1,Tensão_2,Tensão_3,Corrente_1,Corrente_2,Corrente_3
0,3.0,60.0,1740,1.25,18.5,220.0,380.0,440.0,8.89,5.13,4.44

Agora temos efetivamente dados prontos para análise matemática.

Por exemplo, podemos calcular:

In [28]:
df_numerico["Potência"].mean()

np.float64(3.0)